services:
  - type: web
    name: bite-and-sip-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: biteandsip-db
          property: connectionString
      - key: SECRET_KEY
        value: $=)5pubgns!$3b^j0!1y40vx3gp*l32thob*gb_$p75j)!6cxa

